apiVersion: v1
description: Bookinfo Details Service Helm Chart
name: bookinfo-details
version: 1.0.0
appVersion: 1.0.0
home: http://sitkmutt.bookinfo.dev.opsta.net/student33/details
maintainers:
  - name: student33
    email: siriwan.tatar@mail.kmutt.ac.th
sources:
  - https://github.com/tatarsrw/sitkmutt-bookinfo-details